### ISSUE TITLE
Прошу добавить поддержку выключателя 090615.switch.xswitch03

### ISSUE THREAD

**Issue by Fiark** [volshebniks/xiaomi_mijia_ptx#3]
К сожалению не робит выключатель модели 090615.switch.xswitch03 с физическими кнопками.

**Comment by volshebniks** [comment]
попробуйте обновить компонент. может и заработает. у меня нет такого выключателя - так что проверить не могу.

**Comment by Fiark** [comment]
Мистер волшебник, поставил компонент недавно. Единственное различие вроде как в добавлении буквы "х" в названии. А так вроде все точно так же как и на сенсорном на уровне железа

**Comment by Fiark** [comment]
Просто я то не могу добавить букву "х" в конфигурационный ямл, потому что тогда сервак ругается на то что конфигурация не верна. Если сможете поправить то очень поможете ибо на выключателезавязано очень много.

**Comment by volshebniks** [comment]
я сегодня добавил новую версию .. может и заработает.

**Comment by Fiark** [comment]
Спасибо, сегодня попробуем. Если не заработает, то выключатель есть у меня смогу тестировать плагин если согласитесь сотрудничать

**Comment by Fiark** [comment]
Обновил, к сожалению карточка не появилась

**Comment by Fiark** [comment]
и в обьектах тоже не появляется

**Comment by volshebniks** [comment]
Настройки как сделаны?

**Comment by Fiark** [comment]
![image](https://user-images.githubusercontent.com/90027145/146427801-7c576ebc-9af6-455d-bfe7-7425dee34ca1.png)

**Comment by Fiark** [comment]
# Трёхклавишный выключатель    
switch:
  - platform: xiaomi_mijia_ptx
    host: 192.168.0.139
    token: 4817afbc7b36f62b7cb49e66e3512a57
    model: 090615.switch.xswitch03
    name:  Трехклавишный выключатель

**Comment by volshebniks** [comment]
Ошибки в логе есть?
И name попробуйте все ж латиницей.

**Comment by Fiark** [comment]
Какой лог именно смотреть. и имя проьбовал латиницей
в журнале HA было пусто по ошибкам
и устройство в обьектах не появляется - как будто его вообще нет

**Comment by volshebniks** [comment]
настройки - журнал сервера

**Comment by Fiark** [comment]
к сожалению я сейчас не дома и не смогу кинуть конфиг

**Comment by bugavka** [comment]
Настройки:
```
switch:
  - platform: xiaomi_mijia_ptx
    host: 192.168.10.244
    token: !secret token
    model: 090615.switch.xswitch03
    name: Koridor
```
Лог:
```
2021-12-17 15:18:42 ERROR (MainThread) [homeassistant.components.switch] Error while setting up xiaomi_mijia_ptx platform for switch
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
await asyncio.shield(task)
File "/config/custom_components/xiaomi_mijia_ptx/switch.py", line 106, in async_setup_platform
plug = PtxSwitch(host, token, model=model)
File "/config/custom_components/xiaomi_mijia_ptx/ptxswitch.py", line 145, in __init__
self.model = model
AttributeError: can't set attribute
```

**Comment by Fiark** [comment]
Вернулся домой вот ошибка журнала сервера:
2021-12-17 19:33:05 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration yandex_smart_home which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-12-17 19:33:05 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration yandex_station which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-12-17 19:33:05 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-12-17 19:33:05 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration xiaomi_mijia_ptx which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-12-17 19:33:05 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration xiaomi_miio_philipslight which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-12-17 19:33:10 ERROR (MainThread) [homeassistant.components.switch] Error while setting up xiaomi_mijia_ptx platform for switch
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
await asyncio.shield(task)
File "/config/custom_components/xiaomi_mijia_ptx/switch.py", line 106, in async_setup_platform
plug = PtxSwitch(host, token, model=model)
File "/config/custom_components/xiaomi_mijia_ptx/ptxswitch.py", line 145, in __init__
self.model = model
AttributeError: can't set attribute

**Comment by Fiark** [comment]
![image](https://user-images.githubusercontent.com/90027145/146578013-2eb4e2a5-b60a-4173-98c8-a453a0c1b684.png)

**Comment by bugavka** [comment]
возможно, это поможет всем нам ) интеграция Xiaomi Miot Auto поддерживает этот выключатель. Но недавно сбоила. HA начал активно обновляться и переходить на новый python. На данный момент выключатель работает через эту интеграцию.

**Comment by Fiark** [comment]
ну с учетом того что хочется всё локально а не через сервисы xiaomi поэтому не подходит этот вариант

**Comment by bugavka** [comment]
@Fiark разработчик интеграция Xiaomi Miot Auto допилил ее, теперь работает и локально

**Comment by nartovm** [comment]
Без малейшего понятия, куда ещё написать, но проблема такая: тоже владею трёхклавишной версией и без понятия, где достать токен. Во всех других девайсах в ми хоум от vevs токен выцепляется, но в этом выключателе нет, так как меню сильно отличается. Вы где брали?
UPD: отвечу сам себе Xiaomi cloud token extractor на гитхабе
